apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  primary.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby = on
  replica.conf: |
    primary_conninfo = 'host=postgresql-0.postgresql-headless user=postgres password=yourpassword'
    hot_standby = on