apiVersion: v1
kind: Service
metadata:
  name: psql-api
  namespace: {{.Values.namespace}}
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - name: psql-api
    port: 5432
    protocol: TCP