apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: {{.Value.namespace}}
spec:
  serviceName: postgresql
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: postgres_password
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - name: psql-api
          protocol: TCP
          containerPort: 5432
        volumeMounts:
        - name: psql-pvc
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: psql-pvc
      namespace: {{ .Values.namespace }}
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ .Values.storage.class_name }}
      resources:
        requests:
          storage: {{ .Values.storage.size }}
